service: blockchain-against-humanity-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get
